question_data = [
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Han Solo's co-pilot and best friend, 'Chewbacca', is an Ewok.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "text": "There aren't any live-action clones in 'Star Wars: Episode III - Revenge of the Sith'.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "The word 'Inception' came from the 2010 blockbuster hit 'Inception'.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "text": "The colour of the pills in the Matrix were Blue and Yellow.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In the original script of 'The Matrix', the machines used humans as additional computing power instead of batteries.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "text": "The Xenomorph from the science fiction film 'Alien' has acidic blood.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Shaquille O'Neal appeared in the 1997 film 'Space Jam'.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber during the filming of Star Wars.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In Alfred Hitchcock's film 'Psycho' it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
     "text": "'Cube', 'Cube 2: Hypercube' and 'Cube Zero' were directed by the same person.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "Brandon Routh plays the titular character in the movie 'John Wick'.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "George Lucas directed the entire original Star Wars trilogy.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
     "text": "Joan Cusack starred in the 2009 disaster movie, '2012'.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
     "text": "The weapon Clint Eastwood uses in 'Dirty Harry' was a .44 Automag.",
     "answer": "False"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "text": "'Foodfight!' earned less than $80,000 at box office.",
     "answer": "True"},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "hard",
     "text": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
     "answer": "True"}
]
